# Generated by Django 6.1 on 2026-08-26 21:42

import django.core.validators
import django.db.models.deletion
import inventory.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('code', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Sección de inventario',
                'verbose_name_plural': 'Secciones de inventario',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=40, unique=True, verbose_name='Abreviatura')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=100)),
                ('normalized_abbreviation', models.CharField(db_index=True, editable=False, max_length=40)),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Almacén físico',
                'verbose_name_plural': 'Almacenes físicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, null=True, upload_to=inventory.models.inventory_import_upload_to, verbose_name='Archivo original')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre del archivo')),
                ('status', models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], default='PROCESSING', max_length=20, verbose_name='Estado')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total de filas')),
                ('created_products', models.PositiveIntegerField(default=0, verbose_name='Productos creados')),
                ('matched_products', models.PositiveIntegerField(default=0, verbose_name='Productos relacionados')),
                ('movements_created', models.PositiveIntegerField(default=0, verbose_name='Movimientos creados')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='Filas omitidas')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='inventory.inventorysection', verbose_name='Sección')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='inventory.warehouse', verbose_name='Almacén físico')),
            ],
            options={
                'verbose_name': 'Importación de inventario',
                'verbose_name_plural': 'Importaciones de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=150, verbose_name='Nombre normalizado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='inventory.inventorysection', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['section__order', 'section__name', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('normalized_description', models.CharField(db_index=True, editable=False, max_length=255, verbose_name='Descripción normalizada')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock mínimo')),
                ('image', models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_upload_to, verbose_name='Imagen')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='Categoría')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.inventorysection', verbose_name='Sección')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unitofmeasure', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['section__order', 'section__name', 'description'],
            },
        ),
        migrations.CreateModel(
            name='UnitAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=60, unique=True, verbose_name='Alias')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.unitofmeasure', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Alias de unidad',
                'verbose_name_plural': 'Alias de unidades',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUSTMENT_IN', 'Ajuste positivo'), ('ADJUSTMENT_OUT', 'Ajuste negativo')], max_length=30, verbose_name='Tipo de movimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('previous_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Existencia anterior')),
                ('resulting_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Existencia resultante')),
                ('product_code_snapshot', models.CharField(blank=True, default='', max_length=50, verbose_name='Código histórico')),
                ('product_description_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción histórica')),
                ('unit_snapshot', models.CharField(blank=True, default='', max_length=40, verbose_name='Unidad histórica')),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Importación Excel'), ('SYSTEM', 'Sistema')], default='MANUAL', max_length=20, verbose_name='Origen')),
                ('reference', models.CharField(blank=True, default='', max_length=150, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('is_historical', models.BooleanField(default=False, verbose_name='Movimiento histórico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryimportbatch', verbose_name='Lote de importación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse', verbose_name='Almacén físico')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad disponible')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.warehouse', verbose_name='Almacén físico')),
            ],
            options={
                'verbose_name': 'Existencia',
                'verbose_name_plural': 'Existencias',
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['section', 'normalized_name'], name='inventory_c_section_d25312_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['active'], name='inventory_c_active_b4811c_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('section', 'normalized_name'), name='unique_normalized_category_per_section'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['normalized_description'], name='inventory_p_normali_62fd48_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section', 'normalized_description'], name='inventory_p_section_63add5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['section', 'unit', 'normalized_description'], name='inventory_p_section_1dbc65_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_607069_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='inventory_p_active_ee46da_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='inventory_s_product_cbdc37_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse'], name='inventory_s_warehou_a81054_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='inventory_s_movemen_018f99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['import_batch'], name='inventory_s_import__0c08dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_quantity_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['product', 'warehouse'], name='inventory_s_product_112b63_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_warehouse_stock'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_gte_zero'),
        ),
    ]
