# Generated by Django 6.1 on 2026-08-27 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimportbatch',
            name='reversal_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de anulación'),
        ),
        migrations.AddField(
            model_name='inventoryimportbatch',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de anulación'),
        ),
        migrations.AddField(
            model_name='inventoryimportbatch',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_inventory_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Anulada por'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='inventory.stockmovement', verbose_name='Movimiento revertido'),
        ),
        migrations.AlterField(
            model_name='inventoryimportbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Procesando'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida'), ('REVERSED', 'Anulada')], default='PROCESSING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reversal_of'], name='inventory_s_reversa_fa4789_idx'),
        ),
    ]
