# Generated by Django 6.1 on 2026-08-28 01:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_inventoryimportbatch_reversal_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='Número de nota')),
                ('delivered_by_name', models.CharField(max_length=200, verbose_name='Entrega')),
                ('delivered_by_document', models.CharField(max_length=40, verbose_name='Cédula de quien entrega')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Recibe')),
                ('recipient_document', models.CharField(max_length=40, verbose_name='Cédula de quien recibe')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='inventory.warehouse', verbose_name='Almacén de origen')),
            ],
            options={
                'verbose_name': 'Nota de entrega',
                'verbose_name_plural': 'Notas de entrega',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('product_code_snapshot', models.CharField(blank=True, default='', max_length=50, verbose_name='Código histórico')),
                ('product_description_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción histórica')),
                ('unit_snapshot', models.CharField(blank=True, default='', max_length=40, verbose_name='Unidad histórica')),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='documents.deliverynote', verbose_name='Nota de entrega')),
                ('movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note_item', to='inventory.stockmovement', verbose_name='Movimiento de salida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_note_items', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de nota de entrega',
                'verbose_name_plural': 'Ítems de notas de entrega',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['number'], name='documents_note_number_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['delivery_date'], name='documents_note_date_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['warehouse'], name='documents_note_warehouse_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverynoteitem',
            index=models.Index(fields=['delivery_note', 'product'], name='doc_note_item_prod_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverynoteitem',
            constraint=models.UniqueConstraint(fields=('delivery_note', 'product'), name='unique_product_per_delivery_note'),
        ),
    ]
